### ISSUE TITLE
RangeError from recursive calls to hasBinary

### ISSUE THREAD

**Issue by jombles** [Prozi/detect-collisions#7]
I'm hitting a Maximum call stack size exceeded. Error output is below. The only things I'm doing are creating a system, and adding a Polygon and Circle. I'm not sure if this is an internal issue in detect-collisions or something I'm doing wrong.

```
/sandbox/node_modules/has-binary2/index.js:58
    if (Object.prototype.hasOwnProperty.call(obj, key) && hasBinary(obj[key])) {
                                        ^

RangeError: Maximum call stack size exceeded
    at BVH.hasOwnProperty (<anonymous>)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:41)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/sandbox/node_modules/has-binary2/index.js:58:59)

```

**Comment by Prozi** [comment]
I'm actually using this library here www.vikingsvillage.io and I'm doing much more than such simple tasks.

Please share the code snippet of a working example that leads to this error and I can try to help you with your code @jombles

**Comment by Prozi** [comment]
@jombles please check https://github.com/Prozi/detect-collisions/tree/master/demo/examples
